### ISSUE TITLE
[MacOS] Error updating from v0.0.11 to v0.0.13: App initialization error

### ISSUE THREAD

**Issue by damywise** [IsmailAlamKhan/adb_ui#21]
**Describe the bug**
`App Initialization Error`
```
Error requesting environment: /bin/sh: /Users/XXX/Library/Containers/com.adb-ui/Data/ Library/Application Support/com.adb-ui/env.sh: /bin/sh: bad interpreter: Operation not permitted
```

**To Reproduce**
1. Install app
2. Open app

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25608913/200433662-92a1ac03-7208-430a-86d6-1f620f35c863.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6

**Comment by IsmailAlamKhan** [comment]
Ok it looks the dmg created by the gh actions doesn't have enough permission 🤔🤔.

**Comment by roipeker** [comment]
Yep, same issue here from the dmg in [release v0.0.13](https://github.com/IsmailAlamKhan/adb_ui/releases/tag/v0.0.13).

Probably we need to sign the app.

**Comment by damywise** [comment]
Yeah it's because the sandbox mode is enabled

**Comment by roipeker** [comment]
I just compiled the latest from master channel.

@damywise , can you check if [this build](https://we.tl/t-lnRwhWvDAh) works for you?

**Comment by damywise** [comment]
Yup it works

**Comment by IsmailAlamKhan** [comment]
wait the issue is not really fixed cause we need to fix the mac os build from gh actions

**Comment by IsmailAlamKhan** [comment]
@damywise could you please try this release? https://github.com/IsmailAlamKhan/adb_ui/releases/tag/v0.0.0

**Comment by damywise** [comment]
It works now

**Comment by IsmailAlamKhan** [comment]
@damywise thanks a lot for trying out appreciate it.

**Comment by damywise** [comment]
It works now
