### ISSUE TITLE
Clarify push file selection

### ISSUE THREAD

**Issue by clragon** [IsmailAlamKhan/adb_ui#8]
**Is your feature request related to a problem? Please describe.**
The push file selection does not make it immediately clear what happens after a file is selected

**Describe the solution you'd like**
The screen could have a small notice to tell the user that the following files are going to be uploaded, instead of only displaying the file name.

**Comment by IsmailAlamKhan** [comment]
![image](https://user-images.githubusercontent.com/67656229/198527723-94a8313c-0edf-41cf-ac69-3191003a560f.png)
Is this enough?
