### ISSUE TITLE
Allow naming devices

### ISSUE THREAD

**Issue by clragon** [IsmailAlamKhan/adb_ui#9]
**Is your feature request related to a problem? Please describe.**
All my devices are simply named "device", making it difficult to distinguish them.

**Describe the solution you'd like**
Allow naming devices based on host ID.

**Comment by IsmailAlamKhan** [comment]
Now devices will use the model to show like this
![image](https://user-images.githubusercontent.com/67656229/198537960-aaad5004-4a33-47b1-ab12-23db9d4c8aae.png)
